apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAafG4lUTW3ytIegP40f7uup73c6d2CuJ+0R5stUczKdCM18TlS5vJsevuVGXE+LeqX71PxYItfTpiL14yLVlc+q1Ie+QwW4heihLHJpZp7OJsk/usBE1CsOwXE//FwVEqm9UnSmHFDJnbi/6INAggQtZHxqllUkPhMczs58c9TRXogF6LVUst3SLGP5SxPDL1jFKOZqC6cUd4IqrMKKTQG2Rl6BwovYbuBY7aXayIq79OKj7FPWKSGFJWT6ofyq+ghbLerqD8x0QT6eAKTWzwCm8P4OEuqBPGJjj10nGIbSpgYBewdWg0Ol23h2doeoP9by+Ti38ny9lxFPQ6m+5IOatDYAu/bZMEk7SXH+ple1NKXP85DjIbHo+E8KTBwXH/L7BH7ZE+jWqm2RQtsQvSJmo1sd1aQkmmBFvsyQ99mLy6hRz5m5pakfehD3Tr+v6DTkT7cZrrXJkiBzYNJO3iqMwxdDq1Bek4JYouIq9modTzQbsIdJQ+DdyokFrxp65MjnB+0ZA2h4ZSb+w5NKqQttHBha2y4TV9PfpEb28huheH29OlnXJgdB7P302oB8lLZW2gAoc0MEIkMF1qXupTSUNq0c/CgvpojmiAVe0ARMnpxhnGTa2i5nQxVmchqG0/iyXn65fSANyskit80jveLDR8+ARHheA9xskt4IuE2R51XqRm+djjMqZb9yOG5qKynyLmH6Lk=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
